package pgintegration

import (
	"context"
	"sort"
	"testing"

	"github.com/ErasedKyte/Central-Config-Stream/internal/flagsconfig"
	"github.com/ErasedKyte/Central-Config-Stream/internal/microconfig"
)

// The migrations are applied by every test in this package, so a file that no
// longer applies fails everywhere at once. This test is the one that says so in
// one line instead of forty, and it pins the set of tables the DDL is supposed
// to produce — a table added to internal/database/sqlite.go and forgotten in
// migrations/ is exactly the divergence docs/PRODUCTION_READINESS.md §3.5
// describes, and it used to be invisible because nothing ever ran the DDL.
func TestMigrationsCreateTheWholeSchema(t *testing.T) {
	s := newStack(t)

	rows, err := s.DB.Query(`
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = $1 ORDER BY table_name`, s.Schema)
	if err != nil {
		t.Fatalf("read the schema: %v", err)
	}
	defer rows.Close()

	var got []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			t.Fatalf("scan table name: %v", err)
		}
		got = append(got, name)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("read the schema: %v", err)
	}

	want := []string{
		"config_audit_log",
		"config_environments",
		"config_flag",
		"config_flag_value",
		"config_localization",
		"config_microservice_appsettings",
		"config_microservices",
	}
	sort.Strings(want)
	if len(got) != len(want) {
		t.Fatalf("migrations produced %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("migrations produced %v, want %v", got, want)
		}
	}
}

// UPDATED_AT and OCCURRED_AT are TIMESTAMPTZ and not TIMESTAMP, and that is the
// one type choice in migrations/001 that fixes a live bug rather than
// translating a spelling: a naive column stores whatever wall clock the session
// happens to be in, so the reconciler's `UPDATED_AT >= $1` against a bound
// instant is silently wrong by the session's whole UTC offset. The behavioural
// consequence is pinned by TestReconcileWindowIgnoresTheSessionTimeZone; this
// test names the cause, so that "simplifying" the column type back turns one
// test red with an unmistakable message rather than several with a puzzling one.
func TestTimestampColumnsAreTimezoneAware(t *testing.T) {
	s := newStack(t)

	columns := map[string]string{
		"config_environments":             "updated_at",
		"config_microservices":            "updated_at",
		"config_flag":                     "updated_at",
		"config_flag_value":               "updated_at",
		"config_microservice_appsettings": "updated_at",
		"config_localization":             "updated_at",
		"config_audit_log":                "occurred_at",
	}

	for table, column := range columns {
		var dataType string
		err := s.DB.QueryRow(`
			SELECT data_type FROM information_schema.columns
			WHERE table_schema = $1 AND table_name = $2 AND column_name = $3`,
			s.Schema, table, column).Scan(&dataType)
		if err != nil {
			t.Fatalf("read the type of %s.%s: %v", table, column, err)
		}
		if dataType != "timestamp with time zone" {
			t.Errorf("%s.%s is %q, want timestamp with time zone", table, column, dataType)
		}
	}
}

// The seed writes explicit ids into columns declared GENERATED BY DEFAULT AS
// IDENTITY, which does not advance the identity sequence. Unless it is
// restarted, the first generated id is 1 — already taken by seeded environment
// 1 — and a create that had nothing wrong with it comes back as a conflict.
//
// This asserts the fix rather than the symptom: a row created through the
// repository lands above every seeded id, in a table that seeds ids as high as
// 300, so a stranded sequence cannot pass by luck.
func TestSeedDoesNotStrandTheIdentitySequences(t *testing.T) {
	s := newStack(t)
	ctx := context.Background()

	env, err := microconfig.NewPostgresRepository(s.DB).CreateEnvironment(ctx, "sandbox")
	if err != nil {
		t.Fatalf("create environment: %v", err)
	}
	if env.ID <= 3 {
		t.Fatalf("generated environment id %d collides with the seeded 1..3 — the identity sequence was not restarted", env.ID)
	}

	flag, err := flagsconfig.NewPostgresRepository(s.DB).CreateFlag(ctx, flagsconfig.Flag{FlagKey: "generated_id", IsActive: 1})
	if err != nil {
		t.Fatalf("create flag: %v", err)
	}
	if flag.ID <= 9 {
		t.Fatalf("generated flag id %d collides with the seeded 7..9 — the identity sequence was not restarted", flag.ID)
	}
}
