-- central-config: environments reference table (PostgreSQL).
-- One row per deployment stage. Every other table is keyed by it, and the KV
-- keys are environment-scoped ("{ENVIRONMENT_ID}.>"), so the id is part of the
-- public contract with consumers — rows are added, never renumbered.
--
-- APPLY ORDER: the file numbers ARE the apply order. `psql -f` over the
-- directory takes it in lexical order, so a file numbered ahead of a table it
-- has foreign keys into fails on a missing table — number a new file after
-- everything it references. Renumbering an existing file is only free while no
-- deployment has applied the old names; once one has, the numbers are fixed.
--
-- Four conventions this directory relies on, stated once here because 001 is
-- the first file anyone opens.
--
-- 1. Identifiers are unquoted and written in UPPER CASE, matching the
--    repositories' SQL and internal/database/sqlite.go. Postgres folds an
--    unquoted identifier to lower case, and it folds the DDL and the queries
--    the same way, so both sides meet in the middle whatever case they are
--    typed in. Quoting any identifier here would pin it to upper case and break
--    every query that does not quote it — which is all of them. Do not quote.
--
-- 2. Ids are GENERATED BY DEFAULT AS IDENTITY, not ALWAYS. The repositories
--    insert without an id and read the row back by its natural key, so they need
--    generation; but a seed has to be able to supply explicit ids, because the
--    ids are the public contract with consumers and the local stack seeds fixed
--    ones (internal/database/sqlite.go: 1/2/3 for environments, 7/8/9 for flags,
--    100+/200+/300+ for rows). ALWAYS would reject that. The cost of BY DEFAULT
--    is that an explicit insert does not advance the identity sequence, so after
--    seeding by hand run
--        ALTER TABLE <table> ALTER COLUMN ID RESTART WITH <max id + 1>;
--    Skip it and the first generated id collides with a seeded row, which
--    reaches the caller as a 409 nobody asked for.
--
-- 3. Ids, and every column that references one, are BIGINT. The Go models carry
--    every id as int64, so nothing above the database wants a narrower one.
--    CONFIG_AUDIT_LOG is the one that decides it: it is append-only with no
--    retention job shipped, so an INTEGER key there is a countdown rather than
--    a type.
--
-- 4. UPDATED_AT is TIMESTAMPTZ, not TIMESTAMP. This is the one type choice that
--    prevents a live bug rather than merely naming a type. TIMESTAMPTZ stores
--    an instant, so a bound time.Time compares correctly whatever the session's
--    TimeZone is set to, and the reconciler's incremental sweep is a plain
--    `UPDATED_AT >= $1`. A timezone-naive column stores whatever wall clock the
--    session happens to be in instead, so the same comparison is silently
--    offset by the session's whole UTC offset — it matches the wrong rows
--    rather than failing, and every bind has to be converted through the
--    session zone to mean anything at all. Excluding that class of bug is the
--    entire point of the type. Do not "simplify" it back to TIMESTAMP.

CREATE TABLE CONFIG_ENVIRONMENTS (
    ID          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ENVIRONMENT VARCHAR(100) NOT NULL,   -- e.g. 'dev', 'staging', 'prod'
    UPDATED_AT  TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_ENVIRONMENT UNIQUE (ENVIRONMENT)
);
