-- central-config: microservices reference table (PostgreSQL).
-- One row per consuming service. Its id is what the MICROCONFIG and
-- LOCALIZATION KV keys are built from, so it is part of the public contract
-- with consumers — rows are added, never renumbered.

CREATE TABLE CONFIG_MICROSERVICES (
    ID           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MICROSERVICE VARCHAR(100) NOT NULL,   -- e.g. 'catalog-api'
    UPDATED_AT   TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_MICROSERVICE UNIQUE (MICROSERVICE)
);
