-- central-config: environments reference table (Oracle).
-- One row per deployment stage. Every other table is keyed by it, and the KV
-- keys are environment-scoped ("{ENVIRONMENT_ID}.>"), so the id is part of the
-- public contract with consumers — rows are added, never renumbered.
--
-- APPLY ORDER: 001 (CONFIG_LOCALIZATION) references this table and
-- CONFIG_MICROSERVICES, so the file numbers are not the apply order. On a fresh
-- database apply 002 and 003 before 001.

CREATE TABLE CONFIG_ENVIRONMENTS (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ENVIRONMENT VARCHAR2(100) NOT NULL,   -- e.g. 'dev', 'staging', 'prod'
    UPDATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_ENVIRONMENT UNIQUE (ENVIRONMENT)
);
