-- central-config: microservices reference table (Oracle).
-- One row per consuming service. Its id is what the MICROCONFIG and
-- LOCALIZATION KV keys are built from, so it is part of the public contract
-- with consumers — rows are added, never renumbered.

CREATE TABLE CONFIG_MICROSERVICES (
    ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MICROSERVICE VARCHAR2(100) NOT NULL,   -- e.g. 'catalog-api'
    UPDATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_MICROSERVICE UNIQUE (MICROSERVICE)
);
