-- central-config: localization domain table (PostgreSQL).
-- One translation bundle per (microservice, environment, locale).
--
-- BUNDLE_JSON is TEXT and not JSONB, deliberately. The document is republished
-- to KV verbatim, and the publisher skips a write whose bytes are identical to
-- what the bucket already holds — that skip is what stops a full sweep fanning
-- a no-op out to the whole fleet. JSONB is a parsed representation: it re-emits
-- with its own key order and no insignificant whitespace, so every row would
-- read back different from what the admin sent, every sweep would decide every
-- bundle had changed, and the skip would never fire again. TEXT also keeps this
-- column behaving exactly as its SQLite mirror does. Validation stays where it
-- already is — the service refuses anything that is not a top-level JSON object
-- before the row is written.

CREATE TABLE CONFIG_LOCALIZATION (
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MICROSERVICE_ID BIGINT       NOT NULL,
    ENVIRONMENT_ID  BIGINT       NOT NULL,
    LOCALE          VARCHAR(35)  NOT NULL,   -- e.g. 'pt-BR', 'en-US'
    BUNDLE_JSON     TEXT         NOT NULL,   -- { "key": "translation", ... }
    UPDATED_AT      TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOC_MICROSERVICE
        FOREIGN KEY (MICROSERVICE_ID) REFERENCES CONFIG_MICROSERVICES (ID),
    CONSTRAINT FK_LOC_ENVIRONMENT
        FOREIGN KEY (ENVIRONMENT_ID) REFERENCES CONFIG_ENVIRONMENTS (ID),
    CONSTRAINT UQ_LOC_SERVICE_ENV_LOCALE
        UNIQUE (MICROSERVICE_ID, ENVIRONMENT_ID, LOCALE)
);

-- lookup path used by GET /localization/lookup/{msId}/{envId}/{locale}
--
-- Kept as it was under Oracle, but be aware of what it is: UQ_LOC_SERVICE_ENV_LOCALE
-- above is backed by an index on exactly these three columns in this order, so
-- this one is redundant and only costs write amplification. It stays because
-- the repositories' SQL and internal/database/sqlite.go both name it and this
-- port changes dialect, not shape. Dropping it is a separate, deliberate change.
CREATE INDEX IX_LOC_SERVICE_ENV_LOCALE
    ON CONFIG_LOCALIZATION (MICROSERVICE_ID, ENVIRONMENT_ID, LOCALE);
