-- central-config: feature flag definitions (Oracle).
-- The flag key is the human-stable name consumers look a flag up by, and it is
-- the second half of the FLAGS KV key ("{ENVIRONMENT_ID}.{FLAG_KEY}"), so it is
-- restricted to characters a KV key allows and must never contain a dot.

CREATE TABLE CONFIG_FLAG (
    ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FLAG_KEY   VARCHAR2(128) NOT NULL,   -- e.g. 'search_v2'
    IS_ACTIVE  NUMBER(1)     DEFAULT 1 NOT NULL,
    UPDATED_AT TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_FLAG_KEY UNIQUE (FLAG_KEY)
);
