-- central-config: feature flag definitions (PostgreSQL).
-- The flag key is the human-stable name consumers look a flag up by, and it is
-- the second half of the FLAGS KV key ("{ENVIRONMENT_ID}.{FLAG_KEY}"), so it is
-- restricted to characters a KV key allows and must never contain a dot.
--
-- IS_ACTIVE is SMALLINT rather than BOOLEAN, though Postgres has a boolean type
-- that would fit: the flag state is an integer everywhere above this column —
-- the Go model carries int64, the admin
-- API accepts and returns 1/0, and only the KV payload is a real boolean (see
-- "the int/bool trap" in README.md). Switching the column alone would move that
-- conversion into the driver and leave the API contract unchanged, which buys
-- nothing and breaks every scan.

CREATE TABLE CONFIG_FLAG (
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FLAG_KEY   VARCHAR(128) NOT NULL,   -- e.g. 'search_v2'
    IS_ACTIVE  SMALLINT     DEFAULT 1 NOT NULL,
    UPDATED_AT TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_FLAG_KEY UNIQUE (FLAG_KEY)
);
