-- central-config: per-environment feature flag values (Oracle).
-- One row per (environment, flag); this is the row an admin update targets and
-- the row that becomes a FLAGS KV entry.
--
-- VALUE is NOT NULL and carries no default because Oracle stores the empty
-- string as NULL: a caller that wants "no value" writes a placeholder such as
-- 'off' rather than ''.

CREATE TABLE CONFIG_FLAG_VALUE (
    ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ENVIRONMENT_ID NUMBER         NOT NULL,
    FLAG_ID        NUMBER         NOT NULL,
    ENABLED        NUMBER(1)      DEFAULT 0 NOT NULL,
    VALUE          VARCHAR2(4000) NOT NULL,
    UPDATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_FLAG_VALUE_ENVIRONMENT
        FOREIGN KEY (ENVIRONMENT_ID) REFERENCES CONFIG_ENVIRONMENTS (ID),
    CONSTRAINT FK_FLAG_VALUE_FLAG
        FOREIGN KEY (FLAG_ID) REFERENCES CONFIG_FLAG (ID),
    CONSTRAINT UQ_FLAG_VALUE_ENV_FLAG
        UNIQUE (ENVIRONMENT_ID, FLAG_ID)
);

-- The join every read and reconcile does, and the delete that removes a flag's
-- values. UQ_FLAG_VALUE_ENV_FLAG already covers lookups that lead with
-- ENVIRONMENT_ID, so only FLAG_ID needs its own index.
CREATE INDEX IX_FLAG_VALUE_FLAG ON CONFIG_FLAG_VALUE (FLAG_ID);

-- The reconciler's incremental window (WHERE UPDATED_AT >= :since).
CREATE INDEX IX_FLAG_VALUE_UPDATED_AT ON CONFIG_FLAG_VALUE (UPDATED_AT);
