-- central-config: per-environment feature flag values (PostgreSQL).
-- One row per (environment, flag); this is the row an admin update targets and
-- the row that becomes a FLAGS KV entry.
--
-- VALUE is NOT NULL and carries no default, and that is a product decision
-- rather than anything the database forces — read this before relaxing it.
-- Note what NOT NULL does and does not buy on its own: Postgres keeps '' and
-- NULL apart, so the column would accept an empty string happily. Keeping one
-- out is the service's non-empty validation; the constraint closes the other
-- half, and between them a caller who wants "no value" has to write a real
-- placeholder such as 'off'.
--
-- Both stay, because the value is republished to every consumer in the fleet
-- and read as a rollout percentage, a variant name or a threshold; "" arrives
-- at the far end indistinguishable from a parsing bug. If either is ever
-- relaxed, relax both together and decide what a consumer should do with an
-- empty string first.

CREATE TABLE CONFIG_FLAG_VALUE (
    ID             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ENVIRONMENT_ID BIGINT        NOT NULL,
    FLAG_ID        BIGINT        NOT NULL,
    ENABLED        SMALLINT      DEFAULT 0 NOT NULL,
    VALUE          VARCHAR(4000) NOT NULL,
    UPDATED_AT     TIMESTAMPTZ   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_FLAG_VALUE_ENVIRONMENT
        FOREIGN KEY (ENVIRONMENT_ID) REFERENCES CONFIG_ENVIRONMENTS (ID),
    CONSTRAINT FK_FLAG_VALUE_FLAG
        FOREIGN KEY (FLAG_ID) REFERENCES CONFIG_FLAG (ID),
    CONSTRAINT UQ_FLAG_VALUE_ENV_FLAG
        UNIQUE (ENVIRONMENT_ID, FLAG_ID)
);

-- The join every read and reconcile does, and the delete that removes a flag's
-- values. UQ_FLAG_VALUE_ENV_FLAG already covers lookups that lead with
-- ENVIRONMENT_ID, so only FLAG_ID needs its own index.
CREATE INDEX IX_FLAG_VALUE_FLAG ON CONFIG_FLAG_VALUE (FLAG_ID);

-- The reconciler's incremental window (WHERE UPDATED_AT >= $1). Against a
-- TIMESTAMPTZ column that bind is a plain instant comparison — see the
-- TIMESTAMPTZ note in 001.
CREATE INDEX IX_FLAG_VALUE_UPDATED_AT ON CONFIG_FLAG_VALUE (UPDATED_AT);
