-- central-config: per-service appsettings (Oracle).
-- One configuration tree per (microservice, environment), stored
-- whole so a consumer binds a locale-free settings object atomically. It is
-- published verbatim as the MICROCONFIG KV value, which is why the API refuses
-- anything that is not a top-level JSON object.

CREATE TABLE CONFIG_MICROSERVICE_APPSETTINGS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MICROSERVICE_ID NUMBER    NOT NULL,
    ENVIRONMENT_ID  NUMBER    NOT NULL,
    SETTINGS_JSON   CLOB      NOT NULL,   -- { "section": { "key": value }, ... }
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_APPSETTINGS_MICROSERVICE
        FOREIGN KEY (MICROSERVICE_ID) REFERENCES CONFIG_MICROSERVICES (ID),
    CONSTRAINT FK_APPSETTINGS_ENVIRONMENT
        FOREIGN KEY (ENVIRONMENT_ID) REFERENCES CONFIG_ENVIRONMENTS (ID),
    CONSTRAINT UQ_APPSETTINGS_SERVICE_ENV
        UNIQUE (MICROSERVICE_ID, ENVIRONMENT_ID)
);

-- Listing by environment, and the check that refuses to delete an environment
-- still in use. UQ_APPSETTINGS_SERVICE_ENV already covers MICROSERVICE_ID.
CREATE INDEX IX_APPSETTINGS_ENVIRONMENT ON CONFIG_MICROSERVICE_APPSETTINGS (ENVIRONMENT_ID);

-- The reconciler's incremental window (WHERE UPDATED_AT >= :since).
CREATE INDEX IX_APPSETTINGS_UPDATED_AT ON CONFIG_MICROSERVICE_APPSETTINGS (UPDATED_AT);
