-- central-config: per-service appsettings (PostgreSQL).
-- One configuration tree per (microservice, environment), stored
-- whole so a consumer binds a locale-free settings object atomically. It is
-- published verbatim as the SERVICESETTINGS KV value, which is why the API refuses
-- anything that is not a top-level JSON object.
--
-- SETTINGS_JSON is TEXT and not JSONB, for the same reason BUNDLE_JSON is in
-- 003: "published verbatim" and JSONB are incompatible. JSONB would re-emit the
-- document with its own key order and whitespace, so the bytes read back would
-- never match the bytes the admin sent, the publisher's byte-identical skip
-- would stop firing, and every reconcile sweep would republish every tree to
-- the whole fleet.

CREATE TABLE CONFIG_MICROSERVICE_APPSETTINGS (
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MICROSERVICE_ID BIGINT      NOT NULL,
    ENVIRONMENT_ID  BIGINT      NOT NULL,
    SETTINGS_JSON   TEXT        NOT NULL,   -- { "section": { "key": value }, ... }
    UPDATED_AT      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_APPSETTINGS_MICROSERVICE
        FOREIGN KEY (MICROSERVICE_ID) REFERENCES CONFIG_MICROSERVICES (ID),
    CONSTRAINT FK_APPSETTINGS_ENVIRONMENT
        FOREIGN KEY (ENVIRONMENT_ID) REFERENCES CONFIG_ENVIRONMENTS (ID),
    CONSTRAINT UQ_APPSETTINGS_SERVICE_ENV
        UNIQUE (MICROSERVICE_ID, ENVIRONMENT_ID)
);

-- Listing by environment, and the check that refuses to delete an environment
-- still in use. UQ_APPSETTINGS_SERVICE_ENV already covers MICROSERVICE_ID.
CREATE INDEX IX_APPSETTINGS_ENVIRONMENT ON CONFIG_MICROSERVICE_APPSETTINGS (ENVIRONMENT_ID);

-- The reconciler's incremental window (WHERE UPDATED_AT >= $1). See the
-- TIMESTAMPTZ note in 001 for why that bind needs no conversion.
CREATE INDEX IX_APPSETTINGS_UPDATED_AT ON CONFIG_MICROSERVICE_APPSETTINGS (UPDATED_AT);
