-- central-config: admin write audit trail (Oracle).
-- One row per mutating HTTP request (POST/PUT/DELETE); reads are not recorded.
-- The KV buckets only ever hold the current value, so this table is the only
-- place that remembers who flipped a production flag and what they sent.
--
-- Deliberately NOT constrained:
--   * no foreign key on ENVIRONMENT_ID — an audit row has to outlive the
--     environment it refers to, including the request that deleted it;
--   * ACTOR, TARGET_DOMAIN, TARGET_ID and ENVIRONMENT_ID are nullable — a
--     rejected (401) or unrouted (404) write is still worth recording even
--     though nothing is known about its target.
--
-- REQUEST_BODY is stored redacted and truncated by the application (see
-- internal/audit.Redact): secret-shaped fields are masked and the value is
-- capped below the 4000-byte column limit.

CREATE TABLE CONFIG_AUDIT_LOG (
    ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OCCURRED_AT    TIMESTAMP      NOT NULL,
    ACTOR          VARCHAR2(100),                -- configured token name
    METHOD         VARCHAR2(10)   NOT NULL,
    PATH           VARCHAR2(400)  NOT NULL,
    TARGET_DOMAIN  VARCHAR2(40),                 -- e.g. 'flagvalues', 'localization'
    TARGET_ID      VARCHAR2(64),                 -- row id the write targeted
    ENVIRONMENT_ID NUMBER,
    STATUS_CODE    NUMBER(3)      NOT NULL,
    REMOTE_ADDR    VARCHAR2(64),
    REQUEST_BODY   VARCHAR2(4000)
);

-- The two ways the log is read: "what just happened" and "what did this
-- operator do", both over a date range.
CREATE INDEX IX_AUDIT_OCCURRED_AT    ON CONFIG_AUDIT_LOG (OCCURRED_AT);
CREATE INDEX IX_AUDIT_ACTOR_OCCURRED ON CONFIG_AUDIT_LOG (ACTOR, OCCURRED_AT);
